//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawStockQty
    {
        public int Id { get; set; }
        public string MatNumber { get; set; }
        public string MatNR { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Version { get; set; }
        public string FactoryCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual RawStock RawStock { get; set; }
    }
}
