//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawStock
    {
        public RawStock()
        {
            this.RawStockQty = new HashSet<RawStockQty>();
        }
    
        public int Id { get; set; }
        public string MatNR { get; set; }
        public string MatDB { get; set; }
        public string BUn { get; set; }
        public decimal UnitPrice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<RawStockQty> RawStockQty { get; set; }
    }
}
